/**
 * @name 长青SVIP音源(核心API聚合版)
 * @description 以长青二改版核心API为解析器 | tx/kg/kw 三平台全音质(含无损) | HYW+聆澜双链路回退
 * @version v1.5.0
 * @author asice999 (整合)
 * @homepage https://github.com/asice999/lxmusic-sources
 * @update_url https://raw.githubusercontent.com/asice999/lxmusic-sources/master/source.js
 *
 * 架构 (2026-09-23 实测)：
 *   1. 核心API  musicserver.haitangw.cc/v1/music/resolve-url
 *      POST {"source","rid","level"}  实测 tx/kg/kw × 3档音质 = 12/12 全部 201 成功
 *      返回真实官源直链：QQ=isure.stream.qqmusic.qq.com(vkey)
 *                        酷狗=fsdg360.hw.kugou.com / fsandroid.tx.kugou.com
 *                        酷我=car-er.kuwo.cn
 *      wy/mg 返回 UPSTREAM_NO_RESOURCE(503)，无法使用
 *   2. HYW      103.79.184.97/api/music/url   X-Card-Key 认证，tx/kg/kw 3/3 稳定，真实FLAC直链
 *   3. 聆澜     source.shiqianjiang.cn        X-API-Key  认证，tx/kg/kw 3/3 稳定，真实FLAC直链
 *
 * 可用性实测 (2026-09-23)：
 *   tx: 核心API(真QQ直链flac/mp3, 3档) → HYW(3/3) → 聆澜(3/3)
 *   kw: 核心API(car-er.kuwo.cn 真FLAC) → HYW(3/3) → 聆澜(3/3)
 *   kg: 核心API(kugou.com 真FLAC/MP3)  → HYW(3/3) → 聆澜(3/3)
 *   mg: 已剔除 —— 咪咕官方 listen-url v2.2 全返 870001(内部错误)、search API 已下线返回SPA HTML,
 *        核心API对mg返回UPSTREAM_HTTP_5XX, 版权id格式不可得, 确认无解
 *
 * 直链播放性校验 (9/9 通过, Range读首块 + 魔数判定)：
 *   核心API tx/kg/kw lossless → 206 audio/x-flac  fLaC 魔数 ✓
 *   HYW      tx/kg/kw flac    → 206 audio/x-ogg|x-flac fLaC 魔数 ✓
 *   聆澜     tx/kg/kw flac    → 206 audio/x-flac            fLaC 魔数 ✓
 *
 * 关键处理：
 *   1. KuwoDES 直链参数用 $ 作分隔符(bitrate$320&format$mp3)，fixUrl() 统一替换为 = 才能播放
 *   2. QQ/酷狗 vkey 直链有时以 http:// 开头并 301 跳转，verifyUrl 放行 3xx 由播放器跟随
 *   3. 核心API 的 level 仅两档：exhigh(有损) / lossless(无损)，按用户选择音质归一化映射
 *
 * 已剔除失效源：
 *   yinyue.haitangw.net  直链端点全部超时(read timeout) —— v1.3.0 的直链方案已失效
 *   api.liuyunidc.cn     留云 —— 全平台返回同一固定文件(Audio generated by ttsmaker.cn)，非真实歌曲
 *   tang.api.s01s.cn     已被核心API替代(核心API同样返回真QQ直链且覆盖kg/kw)
 *   mobi.kuwo.cn         已被核心API替代(核心API对kw返回更稳定的真FLAC)
 *   musicapi.haitangw.net / cenguigui / bugpk / vkeys / cyapi / ygking / yaohud /
 *   nki / apiv2 / apiv3.kugou.com / music.migu.cn / api-y2.yuafeng.cn /
 *   source.shiqianjiang.cn 的 wy / 103.79.184.97 的 wy
 */
'use strict';

const { EVENT_NAMES, request, on, send } = globalThis.lx;

// ==================== 后端配置 ====================

// 核心API：长青二改版同一后端，支持 tx/kg/kw 三平台多档音质解析
const CORE = {
  url: 'https://musicserver.haitangw.cc/v1/music/resolve-url',
  // 核心API 的 level 参数只有两档有效值
  levelOf: (q) => {
    // 无损类音质全部映射为 lossless
    if (q === 'flac' || q === 'flac24bit' || q === 'master' || q === 'hires' || q === 'atmos') {
      return 'lossless';
    }
    // 其余(128k/192k/320k/空)统一走 exhigh，由平台决定实际码率
    return 'exhigh';
  }
};

// HYW 怡红院：需 X-Card-Key 请求头 + key 查询参数双重认证
const HYW = { api: 'http://103.79.184.97/api/music/url', key: 'PYPW-QFRL-3DBF-95O6' };

// 聆澜：需 X-API-Key 请求头认证
const LL = { api: 'https://source.shiqianjiang.cn/api/music/url', key: 'CERU_KEY-F4A5F0A7-F612-4676-A8F2-4A13DD0FA4E5' };

// 平台白名单：核心API + HYW + 聆澜 三后端共同覆盖
const PLATFORMS = ['tx', 'kg', 'kw'];

const TIMEOUT = 12000;
const CACHE_TTL = 3 * 60 * 1000;
const urlCache = new Map();

// ==================== HTTP 基础 ====================

// 统一的 request 包装：Promise 化 + 统一错误
function httpReq(url, opts) {
  return new Promise((resolve, reject) => {
    request(url, {
      timeout: TIMEOUT,
      method: (opts && opts.method) || 'GET',
      headers: (opts && opts.headers) || {},
      body: (opts && opts.body) !== undefined ? opts.body : undefined
    }, (err, resp, body) => {
      if (err) return reject(new Error('req: ' + (err.message || err)));
      const st = resp && resp.statusCode;
      if (!st || st >= 400) return reject(new Error('HTTP ' + st));
      const b = (resp && resp.body !== undefined) ? resp.body : body;
      if (!b) return reject(new Error('empty body'));
      resolve(typeof b === 'string' ? b : JSON.stringify(b));
    });
  });
}

function jParse(s) {
  try { return JSON.parse(s); } catch (e) { return null; }
}

// KuwoDES 直链的参数分隔符是 $，必须替换为 = 才能被播放器识别为合法查询串
function fixUrl(u) {
  return String(u || '').replace(/\$/g, '=');
}

// 直链存活探测：GET+Range 代替 HEAD(lxmusic request 未必支持 HEAD，直链多返 405 会误杀)
function verifyUrl(url) {
  return new Promise((resolve) => {
    request(url, {
      method: 'GET',
      timeout: 6000,
      headers: { 'User-Agent': 'Mozilla/5.0', 'Range': 'bytes=0-0' },
      body: undefined
    }, (err, resp) => {
      if (err) return resolve(false);
      const st = resp && resp.statusCode;
      // 200/206 资源存在；416 Range 不满足说明资源存在；405 方法受限不代表资源不存在
      // 3xx 重定向说明资源存在(本处 request 不跟随，播放器会跟随 301/302)
      resolve(!!st && (st === 200 || st === 206 || st === 416 || st === 405 ||
        (st >= 300 && st <= 308 && st !== 304)));
    });
  });
}

// ==================== 后端调用 ====================

// 后端1：核心API (POST) —— 三平台官方直链解析器，主链路
async function btCore(platform, id, quality) {
  const s = await httpReq(CORE.url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ source: platform, rid: String(id), level: CORE.levelOf(quality) })
  });
  const j = jParse(s);
  if (!j || j.code !== 0) throw new Error('core: ' + ((j && (j.code || j.message)) || '解析失败'));
  const u = j.data && j.data.url;
  if (!u) throw new Error('core: 无直链');
  return fixUrl(u);
}

// 后端2：HYW —— 真官源直链，三平台回退
async function btHyw(platform, id, quality) {
  const q = 'source=' + encodeURIComponent(platform) +
    '&songId=' + encodeURIComponent(String(id)) +
    '&quality=' + encodeURIComponent(quality || '320k') +
    '&key=' + encodeURIComponent(HYW.key);
  const s = await httpReq(HYW.api + '?' + q, { headers: { 'X-Card-Key': HYW.key } });
  const j = jParse(s);
  if (!j || j.code !== 200 || !j.url) throw new Error('hyw: ' + ((j && (j.message || j.msg)) || 'no url'));
  return fixUrl(j.url);
}

// 后端3：聆澜 —— 真官源直链，三平台回退
async function btLinlan(platform, id, quality) {
  const q = 'source=' + encodeURIComponent(platform) +
    '&songId=' + encodeURIComponent(String(id)) +
    '&quality=' + encodeURIComponent(quality || '320k');
  const s = await httpReq(LL.api + '?' + q, { headers: { 'X-API-Key': LL.key } });
  const j = jParse(s);
  if (!j || j.code !== 200 || !j.url) throw new Error('linlan: ' + ((j && (j.message || j.msg)) || 'no url'));
  return fixUrl(j.url);
}

// ==================== ID 提取 ====================
// lxmusic 回调 info.musicInfo 各平台字段不同，无需映射层：直接取平台原生 ID

// QQ 音乐：mid 是形如 0039MnYb0qxYhV 的串(纯数字则是 songid，非本方案处理对象)
function txMid(mi) {
  if (!mi) return '';
  return (mi.meta && (mi.meta.qq && mi.meta.qq.mid || mi.meta.mid)) ||
    mi.songmid || mi.strMediaMid ||
    (typeof mi.id === 'string' && !/^\d+$/.test(mi.id) ? mi.id : '') || '';
}

// 酷我：rid 数字串
function kwRid(mi) {
  if (!mi) return '';
  return mi.rid || mi.id || mi.songId || mi.musicId || '';
}

// 酷狗：hash 或 albumAudioId
function kgHash(mi) {
  if (!mi) return '';
  return mi.hash || mi.albumAudioId || mi.audioId || '';
}

const ID_FN = { tx: txMid, kw: kwRid, kg: kgHash };

// ==================== 链路编排 ====================
// 每平台统一三级链路：核心API(官源解析) → HYW → 聆澜
const CHAINS = {};
for (const p of PLATFORMS) {
  CHAINS[p] = [
    (id, q) => btCore(p, id, q),   // 主链路：核心API 解析官源直链
    (id, q) => btHyw(p, id, q),    // 回退1：HYW 解析真官源直链
    (id, q) => btLinlan(p, id, q)  // 回退2：聆澜 解析真官源直链
  ];
}

// ==================== 缓存 ====================

function getCache(k) {
  const e = urlCache.get(k);
  if (!e) return null;
  if (Date.now() - e.ts > CACHE_TTL) { urlCache.delete(k); return null; }
  return e.u;
}

function setCache(k, u) {
  if (urlCache.size > 200) urlCache.clear();
  urlCache.set(k, { u: u, ts: Date.now() });
}

// ==================== 主处理 ====================

// 按平台链路顺序解析直链：取直链 → 两次存活探测 → 缓存 → 返回
async function resolve(platform, mi, quality) {
  const idFn = ID_FN[platform];
  const chain = CHAINS[platform];
  if (!idFn || !chain) return Promise.reject(new Error('不支持的平台: ' + platform));

  const id = idFn(mi);
  if (!id) return Promise.reject(new Error(platform + ': 无可用 songId'));

  const q = quality || '320k';
  const ck = platform + ':' + id + ':' + q;
  const hit = getCache(ck);
  if (hit) return hit;

  const errs = [];
  for (const fn of chain) {
    let u = '';
    try {
      u = await fn(id, q);
    } catch (e) {
      errs.push((e && e.message) || 'err');
      continue;
    }
    if (!u || !/^https?:\/\//.test(u)) { errs.push(platform + ':bad-url'); continue; }

    // 两次探测降低瞬时网络抖动导致的误杀
    let alive = false;
    for (let i = 0; i < 2 && !alive; i++) { alive = await verifyUrl(u); }
    if (!alive) { errs.push(platform + ':dead-url'); continue; }

    setCache(ck, u);
    return u;
  }
  return Promise.reject(new Error(platform + ' 全部音源失败: ' + errs.join(' | ')));
}

// ==================== 事件 ====================

on(EVENT_NAMES.request, ({ action, source, info }) => {
  if (action !== 'musicUrl') {
    return Promise.reject(new Error('不支持的 action: ' + action));
  }
  const mi = info && info.musicInfo;
  if (!mi) return Promise.reject(new Error('请求参数不完整'));
  return resolve(source, mi, info && info.type).then(u => Promise.resolve(u));
});

// ==================== 初始化 ====================

send(EVENT_NAMES.inited, {
  openDevTools: false,
  sources: {
    tx: {
      name: 'QQ音乐(核心API+双源聚合)',
      type: 'music',
      actions: ['musicUrl'],
      qualitys: ['128k', '320k', 'flac']
    },
    kw: {
      name: '酷我音乐(核心API+双源聚合)',
      type: 'music',
      actions: ['musicUrl'],
      qualitys: ['128k', '320k', 'flac']
    },
    kg: {
      name: '酷狗音乐(核心API+双源聚合)',
      type: 'music',
      actions: ['musicUrl'],
      qualitys: ['128k', '320k', 'flac']
    }
  }
});
